services:
  - type: web
    name: equipment-management
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
    startCommand: gunicorn equipment_management.wsgi:application

    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: equipment_management.settings
      - key: PYTHON_VERSION
        value: 3.13.4
      - key: DATABASE_URL
        sync: false
      - key: DJANGO_SECRET_KEY
        sync: false
